title: My Web Projects
description: A simple blog powered by Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # replace with your GitHub Pages URL
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-feed
exclude:
  -node_modules
markdown: kramdown
