title: My Web Projects
description: A simple blog powered by Jekyll
baseurl: "/web-projects"
url: "https://mayank0201.github.io"
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-feed
exclude:
  - node_modules
markdown: kramdown
